# ===================================================================== #
#  An R package by Certe:                                               #
#  https://github.com/certe-medical-epidemiology                        #
#                                                                       #
#  Licensed as GPL-v2.0.                                                #
#                                                                       #
#  Developed at non-profit organisation Certe Medical Diagnostics &     #
#  Advice, department of Medical Epidemiology.                          #
#                                                                       #
#  This R package is free software; you can freely use and distribute   #
#  it for both personal and commercial purposes under the terms of the  #
#  GNU General Public License version 2.0 (GNU GPL-2), as published by  #
#  the Free Software Foundation.                                        #
#                                                                       #
#  We created this package for both routine data analysis and academic  #
#  research and it was publicly released in the hope that it will be    #
#  useful, but it comes WITHOUT ANY WARRANTY OR LIABILITY.              #
# ===================================================================== #

on:
  workflow_call:

name: website

jobs:
  website:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Generate Dutch language files for examples
        if: runner.os == 'Linux'
        run: |
          sudo locale-gen nl_NL
          sudo locale-gen nl_NL.UTF-8
          sudo update-locale

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          # use RStudio Package Manager to quickly install packages
          use-public-rspm: true
          # add our own R-universe to install other Certe packages
          extra-repositories: 'https://certe-medical-epidemiology.r-universe.dev'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::pkgdown
            any::remotes
          needs: website

      - name: Install package
        run: |
          Rscript -e 'remotes::install_local()'

      - name: Deploy package
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::build_favicons()'
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE, clean = TRUE)'
